{"name": "Заказы пользователя из раздела \"История заказов\" отображаются на странице \"Лента заказов\"", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\".//li[last()]/a[contains(@href, 'order-history')]/*/p[1]\"}\n  (Session info: chrome=130.0.6723.91); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception\nStacktrace:\n\tGetHandleVerifier [0x01163853+24035]\n\t(No symbol) [0x010EBBE4]\n\t(No symbol) [0x00FCC2D3]\n\t(No symbol) [0x0100DC86]\n\t(No symbol) [0x0100DECB]\n\t(No symbol) [0x0104B9D2]\n\t(No symbol) [0x0102FED4]\n\t(No symbol) [0x0104953F]\n\t(No symbol) [0x0102FC26]\n\t(No symbol) [0x0100218C]\n\t(No symbol) [0x0100310D]\n\tGetHandleVerifier [0x01409683+2800659]\n\tGetHandleVerifier [0x0146423E+3172302]\n\tGetHandleVerifier [0x0145CE52+3142626]\n\tGetHandleVerifier [0x01206C00+692624]\n\t(No symbol) [0x010F4BFD]\n\t(No symbol) [0x010F1908]\n\t(No symbol) [0x010F1AA0]\n\t(No symbol) [0x010E3F50]\n\tBaseThreadInitThunk [0x7621FCC9+25]\n\tRtlGetAppContainerNamedObjectPath [0x778A809E+286]\n\tRtlGetAppContainerNamedObjectPath [0x778A806E+238]", "trace": "self = <test_order_feed.TestOrdersFeed object at 0x0000026D7F775290>, order_feed_page = <pages.feed_page.FeedPage object at 0x0000026D7F839DD0>\npersonal_account = <function personal_account at 0x0000026D7F7E9F80>, main_page = <pages.main_page.MainPage object at 0x0000026D7F879250>\npersonal_account_page = <pages.personal_account_page.PersonalAccountPage object at 0x0000026D7F884150>\n\n    @allure.title('Заказы пользователя из раздела \"История заказов\" отображаются на странице \"Лента заказов\"')\n    def test_displaying_user_orders_in_feeds(self, order_feed_page, personal_account, main_page,\n                                             personal_account_page):\n        main_page.wait_element_invisibility_of_element(10, MainPageLocators.ELEMENT)\n        main_page.drag_and_drop_buns()\n        main_page.click_button_making_an_order()\n        main_page.wait_element_invisibility_of_element(10, MainPageLocators.ELEMENT_ORDER)\n        main_page.close_window_identification_order()\n        main_page.wait_element_element_to_be_clickable(10, MainPageLocators.BUTTON_PERSONAL_ACCOUNT)\n        main_page.click_button_personal_account()\n        personal_account_page.wait_element_invisibility_of_element(10, MainPageLocators.ELEMENT)\n        personal_account_page.transition_to_history_order()\n        personal_account_page.wait_element_invisibility_of_element(10, MainPageLocators.ELEMENT_ORDER)\n>       order_history = personal_account_page.get_text_number_order()\n\ntests\\test_order_feed.py:28: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\npages\\personal_account_page.py:19: in get_text_number_order\n    return self.get_text(PersonalAccountPageLocators.ORDER_HISTORY)\npages\\base_page.py:48: in get_text\n    return self.find_element(locator).text\npages\\base_page.py:20: in find_element\n    return self.driver.find_element(*locator)\n..\\..\\..\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py:748: in find_element\n    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n..\\..\\..\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py:354: in execute\n    self.error_handler.check_response(response)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <selenium.webdriver.remote.errorhandler.ErrorHandler object at 0x0000026D7F786290>\nresponse = {'status': 404, 'value': '{\"value\":{\"error\":\"no such element\",\"message\":\"no such element: Unable to locate element: {\\...\\n\\\\tRtlGetAppContainerNamedObjectPath [0x778A809E+286]\\\\n\\\\tRtlGetAppContainerNamedObjectPath [0x778A806E+238]\\\\n\"}}'}\n\n    def check_response(self, response: Dict[str, Any]) -> None:\n        \"\"\"Checks that a JSON response from the WebDriver does not have an\n        error.\n    \n        :Args:\n         - response - The JSON response from the WebDriver server as a dictionary\n           object.\n    \n        :Raises: If the response contains an error message.\n        \"\"\"\n        status = response.get(\"status\", None)\n        if not status or status == ErrorCode.SUCCESS:\n            return\n        value = None\n        message = response.get(\"message\", \"\")\n        screen: str = response.get(\"screen\", \"\")\n        stacktrace = None\n        if isinstance(status, int):\n            value_json = response.get(\"value\", None)\n            if value_json and isinstance(value_json, str):\n                import json\n    \n                try:\n                    value = json.loads(value_json)\n                    if len(value) == 1:\n                        value = value[\"value\"]\n                    status = value.get(\"error\", None)\n                    if not status:\n                        status = value.get(\"status\", ErrorCode.UNKNOWN_ERROR)\n                        message = value.get(\"value\") or value.get(\"message\")\n                        if not isinstance(message, str):\n                            value = message\n                            message = message.get(\"message\")\n                    else:\n                        message = value.get(\"message\", None)\n                except ValueError:\n                    pass\n    \n        exception_class: Type[WebDriverException]\n        e = ErrorCode()\n        error_codes = [item for item in dir(e) if not item.startswith(\"__\")]\n        for error_code in error_codes:\n            error_info = getattr(ErrorCode, error_code)\n            if isinstance(error_info, list) and status in error_info:\n                exception_class = getattr(ExceptionMapping, error_code, WebDriverException)\n                break\n        else:\n            exception_class = WebDriverException\n    \n        if not value:\n            value = response[\"value\"]\n        if isinstance(value, str):\n            raise exception_class(value)\n        if message == \"\" and \"message\" in value:\n            message = value[\"message\"]\n    \n        screen = None  # type: ignore[assignment]\n        if \"screen\" in value:\n            screen = value[\"screen\"]\n    \n        stacktrace = None\n        st_value = value.get(\"stackTrace\") or value.get(\"stacktrace\")\n        if st_value:\n            if isinstance(st_value, str):\n                stacktrace = st_value.split(\"\\n\")\n            else:\n                stacktrace = []\n                try:\n                    for frame in st_value:\n                        line = frame.get(\"lineNumber\", \"\")\n                        file = frame.get(\"fileName\", \"<anonymous>\")\n                        if line:\n                            file = f\"{file}:{line}\"\n                        meth = frame.get(\"methodName\", \"<anonymous>\")\n                        if \"className\" in frame:\n                            meth = f\"{frame['className']}.{meth}\"\n                        msg = \"    at %s (%s)\"\n                        msg = msg % (meth, file)\n                        stacktrace.append(msg)\n                except TypeError:\n                    pass\n        if exception_class == UnexpectedAlertPresentException:\n            alert_text = None\n            if \"data\" in value:\n                alert_text = value[\"data\"].get(\"text\")\n            elif \"alert\" in value:\n                alert_text = value[\"alert\"].get(\"text\")\n            raise exception_class(message, screen, stacktrace, alert_text)  # type: ignore[call-arg]  # mypy is not smart enough here\n>       raise exception_class(message, screen, stacktrace)\nE       selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\".//li[last()]/a[contains(@href, 'order-history')]/*/p[1]\"}\nE         (Session info: chrome=130.0.6723.91); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception\nE       Stacktrace:\nE       \tGetHandleVerifier [0x01163853+24035]\nE       \t(No symbol) [0x010EBBE4]\nE       \t(No symbol) [0x00FCC2D3]\nE       \t(No symbol) [0x0100DC86]\nE       \t(No symbol) [0x0100DECB]\nE       \t(No symbol) [0x0104B9D2]\nE       \t(No symbol) [0x0102FED4]\nE       \t(No symbol) [0x0104953F]\nE       \t(No symbol) [0x0102FC26]\nE       \t(No symbol) [0x0100218C]\nE       \t(No symbol) [0x0100310D]\nE       \tGetHandleVerifier [0x01409683+2800659]\nE       \tGetHandleVerifier [0x0146423E+3172302]\nE       \tGetHandleVerifier [0x0145CE52+3142626]\nE       \tGetHandleVerifier [0x01206C00+692624]\nE       \t(No symbol) [0x010F4BFD]\nE       \t(No symbol) [0x010F1908]\nE       \t(No symbol) [0x010F1AA0]\nE       \t(No symbol) [0x010E3F50]\nE       \tBaseThreadInitThunk [0x7621FCC9+25]\nE       \tRtlGetAppContainerNamedObjectPath [0x778A809E+286]\nE       \tRtlGetAppContainerNamedObjectPath [0x778A806E+238]\n\n..\\..\\..\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py:229: NoSuchElementException"}, "steps": [{"name": "Ожидание исчезновения элемента", "status": "passed", "parameters": [{"name": "timeout", "value": "10"}, {"name": "locator", "value": "('xpath', './/div[@class= \"Modal_modal_overlay__x2ZCr\"]/parent::div')"}], "start": 1730402873455, "stop": 1730402874042}, {"name": "Перетаскивание булок", "status": "passed", "steps": [{"name": "Перетаскивание Элемента", "status": "passed", "steps": [{"name": "Поиск элемента", "status": "passed", "parameters": [{"name": "locator", "value": "('xpath', \".//a[contains(@href, 'aaa6d')]\")"}], "start": 1730402874045, "stop": 1730402874068}, {"name": "Поиск элемента", "status": "passed", "parameters": [{"name": "locator", "value": "('xpath', \".//span[text() = 'Перетяните булочку сюда (верх)']\")"}], "start": 1730402874068, "stop": 1730402874091}], "parameters": [{"name": "source", "value": "('xpath', \".//a[contains(@href, 'aaa6d')]\")"}, {"name": "target", "value": "('xpath', \".//span[text() = 'Перетяните булочку сюда (верх)']\")"}], "start": 1730402874044, "stop": 1730402874130}], "start": 1730402874043, "stop": 1730402874130}, {"name": "Нажимаем кнопку \"Оформить заказ\"", "status": "passed", "steps": [{"name": "Клик по элементу", "status": "passed", "steps": [{"name": "Поиск элемента", "status": "passed", "parameters": [{"name": "locator", "value": "('xpath', \".//button[text() = 'Оформить заказ']\")"}], "start": 1730402874131, "stop": 1730402874149}], "parameters": [{"name": "locator", "value": "('xpath', \".//button[text() = 'Оформить заказ']\")"}], "start": 1730402874131, "stop": 1730402874211}], "start": 1730402874131, "stop": 1730402874211}, {"name": "Ожидание исчезновения элемента", "status": "passed", "parameters": [{"name": "timeout", "value": "10"}, {"name": "locator", "value": "('xpath', \".//img[contains(@class, 'Modal_modal__loading')]\")"}], "start": 1730402874211, "stop": 1730402876391}, {"name": "Закрываем окно с идентификатором заказа", "status": "passed", "steps": [{"name": "Клик по элементу", "status": "passed", "steps": [{"name": "Поиск элемента", "status": "passed", "parameters": [{"name": "locator", "value": "('xpath', \".//button[contains(@class, 'close')]\")"}], "start": 1730402876391, "stop": 1730402876408}], "parameters": [{"name": "locator", "value": "('xpath', \".//button[contains(@class, 'close')]\")"}], "start": 1730402876391, "stop": 1730402876465}], "start": 1730402876391, "stop": 1730402876465}, {"name": "Ожидание кликабельности элемента", "status": "passed", "parameters": [{"name": "timeout", "value": "10"}, {"name": "locator", "value": "('xpath', \".//p[text() = 'Личный Кабинет']\")"}], "start": 1730402876465, "stop": 1730402876538}, {"name": "Нажимаем на кнопку \"Личный кабинет\"", "status": "passed", "steps": [{"name": "Клик по элементу", "status": "passed", "steps": [{"name": "Поиск элемента", "status": "passed", "parameters": [{"name": "locator", "value": "('xpath', \".//p[text() = 'Личный Кабинет']\")"}], "start": 1730402876539, "stop": 1730402876554}], "parameters": [{"name": "locator", "value": "('xpath', \".//p[text() = 'Личный Кабинет']\")"}], "start": 1730402876539, "stop": 1730402876707}], "start": 1730402876539, "stop": 1730402876708}, {"name": "Ожидание исчезновения элемента", "status": "passed", "parameters": [{"name": "timeout", "value": "10"}, {"name": "locator", "value": "('xpath', './/div[@class= \"Modal_modal_overlay__x2ZCr\"]/parent::div')"}], "start": 1730402876708, "stop": 1730402877298}, {"name": "Переход в раздел \"История заказов\"", "status": "passed", "steps": [{"name": "Клик по элементу", "status": "passed", "steps": [{"name": "Поиск элемента", "status": "passed", "parameters": [{"name": "locator", "value": "('xpath', \".//a[text() = 'История заказов']\")"}], "start": 1730402877299, "stop": 1730402877336}], "parameters": [{"name": "locator", "value": "('xpath', \".//a[text() = 'История заказов']\")"}], "start": 1730402877299, "stop": 1730402877424}], "start": 1730402877298, "stop": 1730402877424}, {"name": "Ожидание исчезновения элемента", "status": "passed", "parameters": [{"name": "timeout", "value": "10"}, {"name": "locator", "value": "('xpath', \".//img[contains(@class, 'Modal_modal__loading')]\")"}], "start": 1730402877424, "stop": 1730402877450}, {"name": "Получение номера заказа", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\".//li[last()]/a[contains(@href, 'order-history')]/*/p[1]\"}\n  (Session info: chrome=130.0.6723.91); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception\nStacktrace:\n\tGetHandleVerifier [0x01163853+24035]\n\t(No symbol) [0x010EBBE4]\n\t(No symbol) [0x00FCC2D3]\n\t(No symbol) [0x0100DC86]\n\t(No symbol) [0x0100DECB]\n\t(No symbol) [0x0104B9D2]\n\t(No symbol) [0x0102FED4]\n\t(No symbol) [0x0104953F]\n\t(No symbol) [0x0102FC26]\n\t(No symbol) [0x0100218C]\n\t(No symbol) [0x0100310D]\n\tGetHandleVerifier [0x01409683+2800659]\n\tGetHandleVerifier [0x0146423E+3172302]\n\tGetHandleVerifier [0x0145CE52+3142626]\n\tGetHandleVerifier [0x01206C00+692624]\n\t(No symbol) [0x010F4BFD]\n\t(No symbol) [0x010F1908]\n\t(No symbol) [0x010F1AA0]\n\t(No symbol) [0x010E3F50]\n\tBaseThreadInitThunk [0x7621FCC9+25]\n\tRtlGetAppContainerNamedObjectPath [0x778A809E+286]\n\tRtlGetAppContainerNamedObjectPath [0x778A806E+238]\n\n", "trace": "  File \"C:\\Users\\Влада\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"C:\\Users\\Влада\\Desktop\\Diplom\\Diplom_3\\pages\\personal_account_page.py\", line 19, in get_text_number_order\n    return self.get_text(PersonalAccountPageLocators.ORDER_HISTORY)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Влада\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"C:\\Users\\Влада\\Desktop\\Diplom\\Diplom_3\\pages\\base_page.py\", line 48, in get_text\n    return self.find_element(locator).text\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Влада\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"C:\\Users\\Влада\\Desktop\\Diplom\\Diplom_3\\pages\\base_page.py\", line 20, in find_element\n    return self.driver.find_element(*locator)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Влада\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 748, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Влада\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 354, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\Влада\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "steps": [{"name": "Получение текста элемента", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\".//li[last()]/a[contains(@href, 'order-history')]/*/p[1]\"}\n  (Session info: chrome=130.0.6723.91); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception\nStacktrace:\n\tGetHandleVerifier [0x01163853+24035]\n\t(No symbol) [0x010EBBE4]\n\t(No symbol) [0x00FCC2D3]\n\t(No symbol) [0x0100DC86]\n\t(No symbol) [0x0100DECB]\n\t(No symbol) [0x0104B9D2]\n\t(No symbol) [0x0102FED4]\n\t(No symbol) [0x0104953F]\n\t(No symbol) [0x0102FC26]\n\t(No symbol) [0x0100218C]\n\t(No symbol) [0x0100310D]\n\tGetHandleVerifier [0x01409683+2800659]\n\tGetHandleVerifier [0x0146423E+3172302]\n\tGetHandleVerifier [0x0145CE52+3142626]\n\tGetHandleVerifier [0x01206C00+692624]\n\t(No symbol) [0x010F4BFD]\n\t(No symbol) [0x010F1908]\n\t(No symbol) [0x010F1AA0]\n\t(No symbol) [0x010E3F50]\n\tBaseThreadInitThunk [0x7621FCC9+25]\n\tRtlGetAppContainerNamedObjectPath [0x778A809E+286]\n\tRtlGetAppContainerNamedObjectPath [0x778A806E+238]\n\n", "trace": "  File \"C:\\Users\\Влада\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"C:\\Users\\Влада\\Desktop\\Diplom\\Diplom_3\\pages\\base_page.py\", line 48, in get_text\n    return self.find_element(locator).text\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Влада\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"C:\\Users\\Влада\\Desktop\\Diplom\\Diplom_3\\pages\\base_page.py\", line 20, in find_element\n    return self.driver.find_element(*locator)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Влада\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 748, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Влада\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 354, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\Влада\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "steps": [{"name": "Поиск элемента", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\".//li[last()]/a[contains(@href, 'order-history')]/*/p[1]\"}\n  (Session info: chrome=130.0.6723.91); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception\nStacktrace:\n\tGetHandleVerifier [0x01163853+24035]\n\t(No symbol) [0x010EBBE4]\n\t(No symbol) [0x00FCC2D3]\n\t(No symbol) [0x0100DC86]\n\t(No symbol) [0x0100DECB]\n\t(No symbol) [0x0104B9D2]\n\t(No symbol) [0x0102FED4]\n\t(No symbol) [0x0104953F]\n\t(No symbol) [0x0102FC26]\n\t(No symbol) [0x0100218C]\n\t(No symbol) [0x0100310D]\n\tGetHandleVerifier [0x01409683+2800659]\n\tGetHandleVerifier [0x0146423E+3172302]\n\tGetHandleVerifier [0x0145CE52+3142626]\n\tGetHandleVerifier [0x01206C00+692624]\n\t(No symbol) [0x010F4BFD]\n\t(No symbol) [0x010F1908]\n\t(No symbol) [0x010F1AA0]\n\t(No symbol) [0x010E3F50]\n\tBaseThreadInitThunk [0x7621FCC9+25]\n\tRtlGetAppContainerNamedObjectPath [0x778A809E+286]\n\tRtlGetAppContainerNamedObjectPath [0x778A806E+238]\n\n", "trace": "  File \"C:\\Users\\Влада\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"C:\\Users\\Влада\\Desktop\\Diplom\\Diplom_3\\pages\\base_page.py\", line 20, in find_element\n    return self.driver.find_element(*locator)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Влада\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 748, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Влада\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 354, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\Влада\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "parameters": [{"name": "locator", "value": "('xpath', \".//li[last()]/a[contains(@href, 'order-history')]/*/p[1]\")"}], "start": 1730402877452, "stop": 1730402880500}], "parameters": [{"name": "locator", "value": "('xpath', \".//li[last()]/a[contains(@href, 'order-history')]/*/p[1]\")"}], "start": 1730402877452, "stop": 1730402880506}], "start": 1730402877450, "stop": 1730402880507}], "parameters": [{"name": "driver", "value": "'chrome'"}], "start": 1730402873455, "stop": 1730402880509, "uuid": "3c2b79a0-d5e0-42f6-9e4d-daf6d013f1b1", "historyId": "4e34257493ad711faf6f925bb9ae42dc", "testCaseId": "05a28f912158aa782186b2fcf63f58b4", "fullName": "tests.test_order_feed.TestOrdersFeed#test_displaying_user_orders_in_feeds", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_order_feed"}, {"name": "subSuite", "value": "TestOrdersFeed"}, {"name": "host", "value": "MSI"}, {"name": "thread", "value": "5804-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_order_feed"}]}