{"uuid": "efcb50fb-c1e9-4080-b519-87862a1c94b7", "children": ["c7d3198e-f03a-42ad-989c-ea0101b7ff30"], "befores": [{"name": "driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 128\nCurrent browser version is 130.0.6723.70 with binary path C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe\nStacktrace:\n\tGetHandleVerifier [0x00007FF68315B632+29090]\n\t(No symbol) [0x00007FF6830CE6E9]\n\t(No symbol) [0x00007FF682F8B1CA]\n\t(No symbol) [0x00007FF682FCD6B2]\n\t(No symbol) [0x00007FF682FCC751]\n\t(No symbol) [0x00007FF682FC729C]\n\t(No symbol) [0x00007FF682FC1E0A]\n\t(No symbol) [0x00007FF68301236D]\n\t(No symbol) [0x00007FF683011A20]\n\t(No symbol) [0x00007FF683006493]\n\t(No symbol) [0x00007FF682FD09B1]\n\t(No symbol) [0x00007FF682FD1B11]\n\tGetHandleVerifier [0x00007FF68347883D+3294125]\n\tGetHandleVerifier [0x00007FF6834C4423+3604371]\n\tGetHandleVerifier [0x00007FF6834BA2E7+3563095]\n\tGetHandleVerifier [0x00007FF683216F16+797318]\n\t(No symbol) [0x00007FF6830D986F]\n\t(No symbol) [0x00007FF6830D5454]\n\t(No symbol) [0x00007FF6830D55E0]\n\t(No symbol) [0x00007FF6830C4A7F]\n\tBaseThreadInitThunk [0x00007FFA7EE87374+20]\n\tRtlUserThreadStart [0x00007FFA7F21CC91+33]\n\n", "trace": "  File \"C:\\Users\\Влада\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"C:\\Users\\Влада\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"C:\\Users\\Влада\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Влада\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Влада\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\_pytest\\fixtures.py\", line 891, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Влада\\Desktop\\Diplom\\Diplom_3\\conftest.py\", line 24, in driver\n    browser = webdriver.Chrome()\n              ^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Влада\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\chrome\\webdriver.py\", line 45, in __init__\n    super().__init__(\n  File \"C:\\Users\\Влада\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\chromium\\webdriver.py\", line 66, in __init__\n    super().__init__(command_executor=executor, options=options)\n  File \"C:\\Users\\Влада\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 212, in __init__\n    self.start_session(capabilities)\n  File \"C:\\Users\\Влада\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 299, in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Влада\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 354, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\Влада\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1730210061799, "stop": 1730210066282}], "start": 1730210061798, "stop": 1730210066378}