{"uuid": "cf0fc4fe-16bc-46d6-9163-2bae1c94546f", "children": ["44697b68-4232-4445-afbc-a60f5637d07b"], "befores": [{"name": "driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 128\nCurrent browser version is 130.0.6723.70 with binary path C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe\nStacktrace:\n\tGetHandleVerifier [0x00007FF6F046B632+29090]\n\t(No symbol) [0x00007FF6F03DE6E9]\n\t(No symbol) [0x00007FF6F029B1CA]\n\t(No symbol) [0x00007FF6F02DD6B2]\n\t(No symbol) [0x00007FF6F02DC751]\n\t(No symbol) [0x00007FF6F02D729C]\n\t(No symbol) [0x00007FF6F02D1E0A]\n\t(No symbol) [0x00007FF6F032236D]\n\t(No symbol) [0x00007FF6F0321A20]\n\t(No symbol) [0x00007FF6F0316493]\n\t(No symbol) [0x00007FF6F02E09B1]\n\t(No symbol) [0x00007FF6F02E1B11]\n\tGetHandleVerifier [0x00007FF6F078883D+3294125]\n\tGetHandleVerifier [0x00007FF6F07D4423+3604371]\n\tGetHandleVerifier [0x00007FF6F07CA2E7+3563095]\n\tGetHandleVerifier [0x00007FF6F0526F16+797318]\n\t(No symbol) [0x00007FF6F03E986F]\n\t(No symbol) [0x00007FF6F03E5454]\n\t(No symbol) [0x00007FF6F03E55E0]\n\t(No symbol) [0x00007FF6F03D4A7F]\n\tBaseThreadInitThunk [0x00007FFAE9557374+20]\n\tRtlUserThreadStart [0x00007FFAE9FFCC91+33]\n\n", "trace": "  File \"C:\\Users\\Влада\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"C:\\Users\\Влада\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"C:\\Users\\Влада\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Влада\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Влада\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\_pytest\\fixtures.py\", line 891, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Влада\\Desktop\\Diplom\\Diplom_3\\conftest.py\", line 24, in driver\n    browser = webdriver.Chrome()\n              ^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Влада\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\chrome\\webdriver.py\", line 45, in __init__\n    super().__init__(\n  File \"C:\\Users\\Влада\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\chromium\\webdriver.py\", line 66, in __init__\n    super().__init__(command_executor=executor, options=options)\n  File \"C:\\Users\\Влада\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 212, in __init__\n    self.start_session(capabilities)\n  File \"C:\\Users\\Влада\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 299, in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Влада\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 354, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\Влада\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1730046250402, "stop": 1730046255965}], "start": 1730046250402, "stop": 1730046256063}